### ISSUE TITLE
Implement a localStorage library

### ISSUE THREAD

**Issue by gilbarbara** [gilbarbara/logos#164]
```
QuotaExceededError: QuotaExceededError: DOM Exception 22
  at setItem ([native code])
  at n (/assets/app.min.js:6:17119)
  at value (/assets/app.min.js:5:26077)
  at value (/assets/app.min.js:5:25916)
  at None ([native code])
```

**Comment by gilbarbara** [comment]
Fixed in 9385f8b0fab8a54d1d8e7590861358c38773c93c
